name: Ci

on: [push, pull_request]

defaults:
  run:
    shell: bash

jobs:
  test:
    name: Test Lint, Format & Build
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        node: [14.x, 16.x]

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup NodeJS
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
          cache: yarn

      - name: Install Dependencies
        run: yarn install

      - name: Format
        run: yarn format:check

      - name: Lint
        run: yarn lint

      - name: Build
        run: yarn build
